package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.FundCompanyDo;

public interface FundCompanyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int deleteByPrimaryKey(String fundCompanyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int insert(FundCompanyDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int insertSelective(FundCompanyDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    FundCompanyDo selectByPrimaryKey(String fundCompanyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(FundCompanyDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int updateByPrimaryKey(FundCompanyDo record);
}