package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.FundArchiveDo;

public interface FundArchiveDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int insert(FundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int insertSelective(FundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    FundArchiveDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(FundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int updateByPrimaryKey(FundArchiveDo record);
}