package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.fundArchiveDo;

public interface fundArchiveDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insert(fundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insertSelective(fundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    fundArchiveDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKeySelective(fundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKey(fundArchiveDo record);
}