package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.fundManagerDo;

public interface fundManagerDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int deleteByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insert(fundManagerDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insertSelective(fundManagerDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    fundManagerDo selectByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKeySelective(fundManagerDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKey(fundManagerDo record);
}