package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.FundDataDo;

public interface FundDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int insert(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int insertSelective(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    FundDataDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 28 23:31:00 CST 2019
     */
    int updateByPrimaryKey(FundDataDo record);
}