package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.fundCompanyDo;

public interface fundCompanyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int deleteByPrimaryKey(String fundCompanyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insert(fundCompanyDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insertSelective(fundCompanyDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    fundCompanyDo selectByPrimaryKey(String fundCompanyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKeySelective(fundCompanyDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundCompany
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKey(fundCompanyDo record);
}