package com.sdu.fund.common.dal.dao;

import com.sdu.fund.common.dal.entity.fundDataDo;

public interface fundDataDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insert(fundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int insertSelective(fundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    fundDataDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKeySelective(fundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    int updateByPrimaryKey(fundDataDo record);
}