package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class fundManagerDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.manager_id
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.manager_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.company_code
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String companyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.company_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.service_date
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Date serviceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.assets_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String assetsScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.best_return
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String bestReturn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.start_working_time
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Date startWorkingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.manager_introduction
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String managerIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.ext_info
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.gmt_create
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundManager.gmt_update
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.manager_id
     *
     * @return the value of fundManager.manager_id
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.manager_id
     *
     * @param managerId the value for fundManager.manager_id
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.manager_name
     *
     * @return the value of fundManager.manager_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.manager_name
     *
     * @param managerName the value for fundManager.manager_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.company_code
     *
     * @return the value of fundManager.company_code
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.company_code
     *
     * @param companyCode the value for fundManager.company_code
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.company_name
     *
     * @return the value of fundManager.company_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.company_name
     *
     * @param companyName the value for fundManager.company_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.service_date
     *
     * @return the value of fundManager.service_date
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Date getServiceDate() {
        return serviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.service_date
     *
     * @param serviceDate the value for fundManager.service_date
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.assets_scale
     *
     * @return the value of fundManager.assets_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getAssetsScale() {
        return assetsScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.assets_scale
     *
     * @param assetsScale the value for fundManager.assets_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setAssetsScale(String assetsScale) {
        this.assetsScale = assetsScale == null ? null : assetsScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.best_return
     *
     * @return the value of fundManager.best_return
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getBestReturn() {
        return bestReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.best_return
     *
     * @param bestReturn the value for fundManager.best_return
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setBestReturn(String bestReturn) {
        this.bestReturn = bestReturn == null ? null : bestReturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.start_working_time
     *
     * @return the value of fundManager.start_working_time
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Date getStartWorkingTime() {
        return startWorkingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.start_working_time
     *
     * @param startWorkingTime the value for fundManager.start_working_time
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setStartWorkingTime(Date startWorkingTime) {
        this.startWorkingTime = startWorkingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.manager_introduction
     *
     * @return the value of fundManager.manager_introduction
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getManagerIntroduction() {
        return managerIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.manager_introduction
     *
     * @param managerIntroduction the value for fundManager.manager_introduction
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setManagerIntroduction(String managerIntroduction) {
        this.managerIntroduction = managerIntroduction == null ? null : managerIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.ext_info
     *
     * @return the value of fundManager.ext_info
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.ext_info
     *
     * @param extInfo the value for fundManager.ext_info
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.gmt_create
     *
     * @return the value of fundManager.gmt_create
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.gmt_create
     *
     * @param gmtCreate the value for fundManager.gmt_create
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundManager.gmt_update
     *
     * @return the value of fundManager.gmt_update
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundManager.gmt_update
     *
     * @param gmtUpdate the value for fundManager.gmt_update
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}