package com.sdu.fund.common.dal.entity;

import java.util.Date;

public class fundDataDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.fund_code
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String fundCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.fund_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String fundName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.unit_net
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double unitNet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.accumulated_net
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double accumulatedNet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.growth_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double growthRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_1w
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate1w;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_1m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate1m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_3m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate3m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_6m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate6m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_1y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate1y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_2y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate2y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_3y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRate3y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_this_year
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRateThisYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.earning_rate_from_establish
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double earningRateFromEstablish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.source_purchase_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double sourcePurchaseRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.purchase_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double purchaseRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.source_subscribe_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String sourceSubscribeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.subscribe_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String subscribeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.redeem_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String redeemRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.min_purchase_amount
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Double minPurchaseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.assets_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String assetsScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.establish_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String establishScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.share_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String shareScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.manager_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String managerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.trustee_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String trusteeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.service_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String serviceRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.ext_info
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private String extInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.gmt_create
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundData.gmt_update
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.fund_code
     *
     * @return the value of fundData.fund_code
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.fund_code
     *
     * @param fundCode the value for fundData.fund_code
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.fund_name
     *
     * @return the value of fundData.fund_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.fund_name
     *
     * @param fundName the value for fundData.fund_name
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.unit_net
     *
     * @return the value of fundData.unit_net
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getUnitNet() {
        return unitNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.unit_net
     *
     * @param unitNet the value for fundData.unit_net
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setUnitNet(Double unitNet) {
        this.unitNet = unitNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.accumulated_net
     *
     * @return the value of fundData.accumulated_net
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getAccumulatedNet() {
        return accumulatedNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.accumulated_net
     *
     * @param accumulatedNet the value for fundData.accumulated_net
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setAccumulatedNet(Double accumulatedNet) {
        this.accumulatedNet = accumulatedNet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.growth_rate
     *
     * @return the value of fundData.growth_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getGrowthRate() {
        return growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.growth_rate
     *
     * @param growthRate the value for fundData.growth_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setGrowthRate(Double growthRate) {
        this.growthRate = growthRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_1w
     *
     * @return the value of fundData.earning_rate_1w
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate1w() {
        return earningRate1w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_1w
     *
     * @param earningRate1w the value for fundData.earning_rate_1w
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate1w(Double earningRate1w) {
        this.earningRate1w = earningRate1w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_1m
     *
     * @return the value of fundData.earning_rate_1m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate1m() {
        return earningRate1m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_1m
     *
     * @param earningRate1m the value for fundData.earning_rate_1m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate1m(Double earningRate1m) {
        this.earningRate1m = earningRate1m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_3m
     *
     * @return the value of fundData.earning_rate_3m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate3m() {
        return earningRate3m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_3m
     *
     * @param earningRate3m the value for fundData.earning_rate_3m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate3m(Double earningRate3m) {
        this.earningRate3m = earningRate3m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_6m
     *
     * @return the value of fundData.earning_rate_6m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate6m() {
        return earningRate6m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_6m
     *
     * @param earningRate6m the value for fundData.earning_rate_6m
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate6m(Double earningRate6m) {
        this.earningRate6m = earningRate6m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_1y
     *
     * @return the value of fundData.earning_rate_1y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate1y() {
        return earningRate1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_1y
     *
     * @param earningRate1y the value for fundData.earning_rate_1y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate1y(Double earningRate1y) {
        this.earningRate1y = earningRate1y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_2y
     *
     * @return the value of fundData.earning_rate_2y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate2y() {
        return earningRate2y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_2y
     *
     * @param earningRate2y the value for fundData.earning_rate_2y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate2y(Double earningRate2y) {
        this.earningRate2y = earningRate2y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_3y
     *
     * @return the value of fundData.earning_rate_3y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRate3y() {
        return earningRate3y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_3y
     *
     * @param earningRate3y the value for fundData.earning_rate_3y
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRate3y(Double earningRate3y) {
        this.earningRate3y = earningRate3y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_this_year
     *
     * @return the value of fundData.earning_rate_this_year
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRateThisYear() {
        return earningRateThisYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_this_year
     *
     * @param earningRateThisYear the value for fundData.earning_rate_this_year
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRateThisYear(Double earningRateThisYear) {
        this.earningRateThisYear = earningRateThisYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.earning_rate_from_establish
     *
     * @return the value of fundData.earning_rate_from_establish
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getEarningRateFromEstablish() {
        return earningRateFromEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.earning_rate_from_establish
     *
     * @param earningRateFromEstablish the value for fundData.earning_rate_from_establish
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEarningRateFromEstablish(Double earningRateFromEstablish) {
        this.earningRateFromEstablish = earningRateFromEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.source_purchase_rate
     *
     * @return the value of fundData.source_purchase_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getSourcePurchaseRate() {
        return sourcePurchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.source_purchase_rate
     *
     * @param sourcePurchaseRate the value for fundData.source_purchase_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setSourcePurchaseRate(Double sourcePurchaseRate) {
        this.sourcePurchaseRate = sourcePurchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.purchase_rate
     *
     * @return the value of fundData.purchase_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getPurchaseRate() {
        return purchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.purchase_rate
     *
     * @param purchaseRate the value for fundData.purchase_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setPurchaseRate(Double purchaseRate) {
        this.purchaseRate = purchaseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.source_subscribe_rate
     *
     * @return the value of fundData.source_subscribe_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getSourceSubscribeRate() {
        return sourceSubscribeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.source_subscribe_rate
     *
     * @param sourceSubscribeRate the value for fundData.source_subscribe_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setSourceSubscribeRate(String sourceSubscribeRate) {
        this.sourceSubscribeRate = sourceSubscribeRate == null ? null : sourceSubscribeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.subscribe_rate
     *
     * @return the value of fundData.subscribe_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getSubscribeRate() {
        return subscribeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.subscribe_rate
     *
     * @param subscribeRate the value for fundData.subscribe_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setSubscribeRate(String subscribeRate) {
        this.subscribeRate = subscribeRate == null ? null : subscribeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.redeem_rate
     *
     * @return the value of fundData.redeem_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getRedeemRate() {
        return redeemRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.redeem_rate
     *
     * @param redeemRate the value for fundData.redeem_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setRedeemRate(String redeemRate) {
        this.redeemRate = redeemRate == null ? null : redeemRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.min_purchase_amount
     *
     * @return the value of fundData.min_purchase_amount
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Double getMinPurchaseAmount() {
        return minPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.min_purchase_amount
     *
     * @param minPurchaseAmount the value for fundData.min_purchase_amount
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setMinPurchaseAmount(Double minPurchaseAmount) {
        this.minPurchaseAmount = minPurchaseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.assets_scale
     *
     * @return the value of fundData.assets_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getAssetsScale() {
        return assetsScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.assets_scale
     *
     * @param assetsScale the value for fundData.assets_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setAssetsScale(String assetsScale) {
        this.assetsScale = assetsScale == null ? null : assetsScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.establish_scale
     *
     * @return the value of fundData.establish_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getEstablishScale() {
        return establishScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.establish_scale
     *
     * @param establishScale the value for fundData.establish_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setEstablishScale(String establishScale) {
        this.establishScale = establishScale == null ? null : establishScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.share_scale
     *
     * @return the value of fundData.share_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getShareScale() {
        return shareScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.share_scale
     *
     * @param shareScale the value for fundData.share_scale
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setShareScale(String shareScale) {
        this.shareScale = shareScale == null ? null : shareScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.manager_rate
     *
     * @return the value of fundData.manager_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getManagerRate() {
        return managerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.manager_rate
     *
     * @param managerRate the value for fundData.manager_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setManagerRate(String managerRate) {
        this.managerRate = managerRate == null ? null : managerRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.trustee_rate
     *
     * @return the value of fundData.trustee_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getTrusteeRate() {
        return trusteeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.trustee_rate
     *
     * @param trusteeRate the value for fundData.trustee_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setTrusteeRate(String trusteeRate) {
        this.trusteeRate = trusteeRate == null ? null : trusteeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.service_rate
     *
     * @return the value of fundData.service_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getServiceRate() {
        return serviceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.service_rate
     *
     * @param serviceRate the value for fundData.service_rate
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setServiceRate(String serviceRate) {
        this.serviceRate = serviceRate == null ? null : serviceRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.ext_info
     *
     * @return the value of fundData.ext_info
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.ext_info
     *
     * @param extInfo the value for fundData.ext_info
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.gmt_create
     *
     * @return the value of fundData.gmt_create
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.gmt_create
     *
     * @param gmtCreate the value for fundData.gmt_create
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundData.gmt_update
     *
     * @return the value of fundData.gmt_update
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundData.gmt_update
     *
     * @param gmtUpdate the value for fundData.gmt_update
     *
     * @mbg.generated Thu Nov 21 20:12:48 CST 2019
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}