package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.FundDataDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FundDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Sun Feb 09 21:20:09 CST 2020
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Sun Feb 09 21:20:09 CST 2020
     */
    int insert(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Sun Feb 09 21:20:09 CST 2020
     */
    int insertSelective(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Sun Feb 09 21:20:09 CST 2020
     */
    FundDataDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Sun Feb 09 21:20:09 CST 2020
     */
    int updateByPrimaryKeySelective(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Sun Feb 09 21:20:09 CST 2020
     */
    int updateByPrimaryKey(FundDataDo record);

    List<FundDataDo> selectFundList(@Param("fundType") Integer fundType, @Param("gainType") String gainType, @Param(
            "curIndex") int curIndex, @Param("pageSize") int pageSize);
}