package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.FundManagerDo;

public interface FundManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int deleteByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int insert(FundManagerDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int insertSelective(FundManagerDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    FundManagerDo selectByPrimaryKey(String managerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int updateByPrimaryKeySelective(FundManagerDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundManager
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int updateByPrimaryKey(FundManagerDo record);
}