package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.FundDataDo;

public interface FundDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int insert(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int insertSelective(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    FundDataDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int updateByPrimaryKeySelective(FundDataDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundData
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int updateByPrimaryKey(FundDataDo record);
}