package com.sdu.fund.common.dal.mapper;

import com.sdu.fund.common.dal.entity.FundArchiveDo;

public interface FundArchiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int deleteByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int insert(FundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int insertSelective(FundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    FundArchiveDo selectByPrimaryKey(String fundCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int updateByPrimaryKeySelective(FundArchiveDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundArchive
     *
     * @mbg.generated Thu Dec 05 20:17:23 CST 2019
     */
    int updateByPrimaryKey(FundArchiveDo record);
}